# Generated by Django 4.1.7 on 2023-05-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_name', models.CharField(max_length=100)),
                ('rg_scope', models.CharField(default='No attributed city', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rl_name', models.CharField(max_length=100)),
                ('rl_text', models.CharField(max_length=1000)),
                ('rl_external_reference', models.CharField(max_length=100)),
                ('rl_code', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zn_name', models.CharField(max_length=100)),
                ('zn_regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_regulation.regulation')),
            ],
        ),
    ]
