# Generated by Django 4.1.7 on 2023-05-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zn_rules',
            field=models.ManyToManyField(to='digital_regulation.rule'),
        ),
    ]
