# Generated by Django 4.1.7 on 2023-07-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digital_regulation.zone'),
        ),
    ]
