# Generated by Django 4.1.7 on 2023-10-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='code',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
