# Generated by Django 4.1.7 on 2023-06-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0002_zone_zn_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulation',
            old_name='rg_name',
            new_name='name',
        ),
    ]
