# Generated by Django 4.1.7 on 2023-07-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0002_alter_zone_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='code',
            field=models.TextField(max_length=1000),
        ),
    ]
