# Generated by Django 4.1.7 on 2023-06-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0003_rename_rg_name_regulation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulation',
            old_name='rg_scope',
            new_name='scope',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='rl_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='rl_external_reference',
            new_name='external_reference',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='rl_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='rl_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='zn_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='zn_regulation',
            new_name='regulation',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='zn_rules',
            new_name='rules',
        ),
        migrations.AddField(
            model_name='zone',
            name='zones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digital_regulation.zone'),
        ),
    ]
