# Generated by Django 4.1.7 on 2023-07-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0003_alter_rule_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
