# Generated by Django 4.1.7 on 2023-07-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0004_alter_rule_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='code',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
