# Generated by Django 4.1.7 on 2023-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0005_alter_rule_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='blocks',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
