# Generated by Django 4.1.7 on 2023-07-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0006_rule_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='has_code',
            field=models.BooleanField(default=False),
        ),
    ]
