# Generated by Django 4.1.7 on 2023-07-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0007_rule_has_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='rules',
            field=models.ManyToManyField(blank=True, to='digital_regulation.rule'),
        ),
    ]
