# Generated by Django 4.1.7 on 2023-07-04 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital_regulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('regulations', models.ManyToManyField(to='digital_regulation.regulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UrbanisticOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_isolated', models.BooleanField(default=True)),
                ('use', models.CharField(default='', max_length=200)),
                ('ifc_file', models.FileField(upload_to='ifc_files/')),
                ('xkt_file', models.CharField(max_length=100)),
                ('model_processed', models.BooleanField(default=False)),
                ('urbanistic_operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.urbanisticoperation')),
            ],
        ),
    ]
