# Generated by Django 4.1.7 on 2023-07-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='is_isolated',
        ),
        migrations.AlterField(
            model_name='urbanisticoperation',
            name='type',
            field=models.CharField(choices=[('CONSTRUCAO', 'construção'), ('ALTERACAO', 'alteração'), ('AMPLIACAO', 'ampliação')], max_length=200),
        ),
    ]
