# Generated by Django 4.1.7 on 2023-07-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_building_is_isolated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='use',
        ),
    ]
