# Generated by Django 4.1.7 on 2023-06-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_pj_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmodel',
            name='bm_xkt_file',
            field=models.CharField(max_length=100),
        ),
    ]
