# Generated by Django 4.1.7 on 2023-06-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_buildingmodel_bm_xkt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmodel',
            name='bm_model_processed',
            field=models.BooleanField(default=False),
        ),
    ]
