# Generated by Django 4.1.7 on 2023-06-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_buildingmodel_bm_model_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='buildingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_is_isolated', models.BooleanField(default=True)),
                ('bm_ifc_file', models.FileField(upload_to='ifc_files/')),
                ('bm_xkt_file', models.CharField(max_length=100)),
                ('bm_model_processed', models.BooleanField(default=False)),
                ('bm_urbanistic_operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.urbanisticoperation')),
            ],
        ),
        migrations.DeleteModel(
            name='buildingmodel',
        ),
    ]
