# Generated by Django 4.1.7 on 2023-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='bm_ifc_file',
            new_name='ifc_file',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='bm_is_isolated',
            new_name='is_isolated',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='bm_model_processed',
            new_name='model_processed',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='bm_urbanistic_operation',
            new_name='urbanistic_operation',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='bm_xkt_file',
            new_name='xkt_file',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pj_date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pj_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pj_regulations',
            new_name='regulations',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pj_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='urbanisticoperation',
            old_name='uo_adress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='urbanisticoperation',
            old_name='uo_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='urbanisticoperation',
            old_name='uo_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='building',
            name='use',
            field=models.CharField(default='', max_length=200),
        ),
    ]
