# Generated by Django 4.1.7 on 2023-10-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital_regulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_executed', models.DateTimeField(auto_now_add=True)),
                ('ifc_file', models.FileField(upload_to='ifc_files/')),
                ('report', models.CharField(blank=True, default='', max_length=200)),
                ('regulations', models.ManyToManyField(blank=True, to='digital_regulation.regulation')),
            ],
        ),
        migrations.CreateModel(
            name='RuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_ids', models.TextField(max_length=20000)),
                ('result', models.BooleanField()),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.verification')),
            ],
        ),
    ]
