# Generated by Django 4.1.7 on 2023-05-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to='')),
                ('regulation', models.FileField(upload_to='')),
                ('result', models.CharField(blank=True, default='Not executed', max_length=100)),
                ('date_executed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
