# Generated by Django 4.1.7 on 2023-06-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='vf_model',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='vf_model_rules',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='verification',
            name='vf_regulations',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='verification',
            name='vf_report',
            field=models.CharField(default='', max_length=200),
        ),
    ]
