# Generated by Django 4.1.7 on 2023-05-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='model',
            field=models.FileField(upload_to='ifc_file/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='regulation',
            field=models.FileField(upload_to='digital_regulations/'),
        ),
    ]
