# Generated by Django 4.1.7 on 2023-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='ifc_file',
            field=models.FileField(blank=True, upload_to='ifc_files/'),
        ),
    ]
