# Generated by Django 4.1.7 on 2023-07-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='report',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
