# Generated by Django 4.1.7 on 2023-10-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_verification_ifc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='xkt_file',
            field=models.FileField(blank=True, upload_to='xkt_files/'),
        ),
    ]
