# Generated by Django 4.1.7 on 2023-06-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_buildingmodel_bm_model_processed'),
        ('verification', '0002_verification_vf_model_verification_vf_model_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='vf_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
