# Generated by Django 4.1.7 on 2023-06-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_regulation', '0002_zone_zn_rules'),
        ('verification', '0003_alter_verification_vf_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='vf_regulations',
        ),
        migrations.AddField(
            model_name='verification',
            name='vf_regulations',
            field=models.ManyToManyField(to='digital_regulation.regulation'),
        ),
    ]
