# Generated by Django 4.1.7 on 2023-10-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_verification_xkt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='report',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
