# Generated by Django 4.1.7 on 2023-10-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_alter_verification_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='report',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
