# Generated by Django 4.1.7 on 2023-06-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_remove_verification_vf_regulations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='vf_model',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='vf_model_rules',
        ),
    ]
