# Generated by Django 4.1.7 on 2023-06-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_remove_verification_vf_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='vf_regulations',
        ),
    ]
