# Generated by Django 4.1.7 on 2023-06-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_remove_verification_vf_regulations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='vf_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='vf_report',
            new_name='report',
        ),
    ]
