# Generated by Django 4.1.7 on 2023-02-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autentic", "0002_applicant_regulations_projects_clause"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clause",
            name="code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="clause",
            name="has_code",
            field=models.BooleanField(default=False),
        ),
    ]
