# Generated by Django 4.1.7 on 2023-02-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autentic", "0003_alter_clause_code_alter_clause_has_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clause",
            name="regulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="autentic.regulations",
            ),
        ),
    ]
