# Generated by Django 4.1.7 on 2023-02-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autentic", "0004_alter_clause_regulation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clause",
            name="regulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clauses",
                to="autentic.regulations",
            ),
        ),
    ]
