# Generated by Django 4.1.7 on 2023-02-28 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autentic", "0006_clause_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulations",
            name="came_into_effect",
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name="regulations",
            name="city",
            field=models.CharField(default="No attributed city", max_length=200),
        ),
        migrations.AlterField(
            model_name="clause",
            name="code",
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="clause",
            name="text",
            field=models.CharField(default="No text", max_length=10000),
        ),
    ]
