# Generated by Django 4.1.7 on 2023-04-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentic', '0008_clause_python_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='owner',
        ),
    ]
